name: Release

on:
  push:
    tags:
      - "[0-9]+.*"

jobs:
  create-release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        env:
          # (required)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Targets that match the OS of the runner.
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-20.04

          # Targets using cross-compilation (upload-rust-binary-action
          # detects that they need cross).
          - target: x86_64-unknown-linux-musl
            os: ubuntu-20.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          # (optional) On which platform to distribute the `.tar.gz` file.
          tar: unix
          # (optional) On which platform to distribute the `.zip` file.
          zip: windows
          # (optional) Target triple, default is host triple.
          target: ${{ matrix.target }}
        env:
          # (required)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
